name: Release build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  LSPD_GO_VERSION: 1.21.0
  CLN_REF: v24.02.1

jobs:
  lspd:
    name: Release lspd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go ${{ env.LSPD_GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.LSPD_GO_VERSION }}"

      - name: get tag
        run: |
          echo "TAG=$(git describe --tags --dirty)" >> $GITHUB_ENV

      - name: build lspd
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make release-all

      - name: zip lspd artifacts
        run: tar -czvf lspd-${{ env.TAG }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz lspd lspd_cln_plugin

      - name: upload lspd artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lspd-${{ env.TAG }}-${{ matrix.os }}-${{ matrix.arch }}
          path: lspd-${{ env.TAG }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - lspd
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*.gz"
          generateReleaseNotes: true
          draft: true
